## ------------------------------------------------------------------
## Null Model Simulation: Supplementary Material
##
## Tests whether the observed monotonic propagation of growth-rank
## leadership can arise from plausible alternative mechanisms without
## a travelling-wave structure.
##
## Prices are initialised at the empirical cross-sectional median
## prices from the first month of the price-per-square-metre dataset.
## Monthly log returns are generated by an Ornstein-Uhlenbeck process
## and accumulated into price levels. Twelve-month log returns,
## 2x12-MA smoothing, and growth ranks are then computed using the
## same methodology as the empirical analysis.
##
## The paper shows that log-prices follow a log-logistic cross-
## sectional relationship: l(q,t) = mu(t) + s(t) * logit(q), with
## R-squared > 0.97. Both mu and s evolve over time (the travelling
## wave reshapes the distribution it propagates through). To give
## each null model the best chance, we preserve this functional form
## by projecting log-prices onto the logistic manifold at each step.
## The location mu(t) and scale s(t) are both free to evolve — only
## deviations from the logistic shape are dampened.
##
## Five null models are tested:
##
##   1. Base:            correlated mean-reverting returns (OU)
##   2. Combined:        asymmetric reversion + boom-bust cycle +
##                       leverage effect (strongest independent null)
##   3. Diffusion:       symmetric spatial spreading via discrete
##                       Laplacian on returns
##   4. Spatial AR:      each quantile's return depends on the lagged
##                       return of its more expensive neighbour
##   5. Credit-leverage: common credit factor with heterogeneous
##                       sensitivity by price level
##
## Each specification is simulated at three correlation lengths.
## ------------------------------------------------------------------

library(tidyverse)
library(slider)
library(plotly)

set.seed(42)

## ── Empirical initial prices ───────────────────────────────────────

setwd("/Users/chrisbeech/Documents/UK housing analysis")

psqm <- read_csv("Data/pp-stampduty-psqm.csv")

n_quantiles <- 10
n_months <- 360 # 30 years

initial_prices <-
  psqm |>
  mutate(Date = floor_date(`Date of Transfer`, "month")) |>
  filter(Date == min(Date)) |>
  mutate(quantile = ntile(Price_inc_Stamp_Duty, n_quantiles)) |>
  group_by(quantile) |>
  summarise(median_price = median(Price_inc_Stamp_Duty), .groups = "drop") |>
  arrange(quantile) |>
  pull(median_price)

## ── Logistic coordinates ──────────────────────────────────────────
## logit(q) values for each quantile, used for shape projection.

q_vals <- ((1:n_quantiles) - 0.5) / n_quantiles
logit_q <- log(q_vals / (1 - q_vals))

## ── Pre-generated credit cycle (for model 5) ──────────────────────

credit_series <- numeric(n_months)
for (t in 2:n_months) {
  credit_series[t] <- 0.98 * credit_series[t - 1] + rnorm(1, 0, 0.003)
}

## ── Helper functions ──────────────────────────────────────────────

generate_correlated_shocks <- function(n_quantiles, n_months, cor_length) {
  cor_matrix <- exp(-abs(outer(1:n_quantiles, 1:n_quantiles, `-`)) / cor_length)
  chol_L <- chol(cor_matrix)
  map(1:n_months, \(t) as.numeric(rnorm(n_quantiles) %*% chol_L)) |>
    do.call(what = rbind)
}

discrete_laplacian <- function(x) {
  n <- length(x)
  lap <- numeric(n)
  lap[2:(n - 1)] <- x[1:(n - 2)] - 2 * x[2:(n - 1)] + x[3:n]
  lap[1] <- x[2] - x[1]
  lap[n] <- x[n - 1] - x[n]
  lap
}

## ── Simulation engine ──────────────────────────────────────────────
## Log-logistic shape preservation: at each step, the current log-
## prices are regressed on logit(q) to find the best-fitting mu(t)
## and s(t). Prices are then pulled toward this fitted logistic.
## Both mu and s are free to evolve — only non-logistic deviations
## (residuals from the fit) are dampened. This preserves the
## functional form that generates the paper's Jacobian without
## constraining the scale parameter s.

shape_reversion <- 0.05

simulate_null <- function(
  n_quantiles,
  n_months,
  cor_length,
  initial_prices,
  mu_fn,
  theta_fn,
  sigma_fn,
  coupling_fn = NULL,
  label
) {
  q_idx <- 1:n_quantiles
  shocks <- generate_correlated_shocks(n_quantiles, n_months, cor_length)

  log_price <- matrix(0, nrow = n_months, ncol = n_quantiles)
  log_price[1, ] <- log(initial_prices)

  r_matrix <- matrix(0, nrow = n_months, ncol = n_quantiles)
  r_matrix[1, ] <- mu_fn(q_idx, 1, rep(0, n_quantiles))

  for (t in 2:n_months) {
    mu_t <- mu_fn(q_idx, t, r_matrix[t - 1, ])
    theta_t <- theta_fn(q_idx, t, r_matrix[t - 1, ])
    sigma_t <- sigma_fn(q_idx, t, r_matrix[t - 1, ])

    r_matrix[t, ] <- r_matrix[t - 1, ] +
      theta_t * (mu_t - r_matrix[t - 1, ]) +
      sigma_t * shocks[t, ]

    if (!is.null(coupling_fn)) {
      r_matrix[t, ] <- r_matrix[t, ] + coupling_fn(r_matrix[t - 1, ])
    }

    log_price[t, ] <- log_price[t - 1, ] + r_matrix[t, ]

    # Project onto log-logistic manifold: fit mu(t), s(t) via OLS
    # then dampen residuals from the fitted logistic
    fit <- .lm.fit(cbind(1, logit_q), log_price[t, ])
    fitted_logistic <- fit$coefficients[1] + fit$coefficients[2] * logit_q
    log_price[t, ] <- log_price[t, ] +
      shape_reversion * (fitted_logistic - log_price[t, ])
  }

  tibble(
    month = rep(1:n_months, each = n_quantiles),
    quantile = rep(1:n_quantiles, times = n_months),
    log_price = as.numeric(t(log_price)),
    label = label
  )
}

## ── Shared parameter functions ───────────────────────────────────

base_mu <- function(q_idx, t, r_prev) {
  (0.04 + 0.02 * (q_idx / max(q_idx))) / 12
}

base_sigma <- function(q_idx, t, r_prev) {
  (0.02 + 0.01 * abs(q_idx / max(q_idx) - 0.5)) / sqrt(12)
}

base_theta <- function(q_idx, t, r_prev) {
  rep(0.05, length(q_idx))
}

## ── Model specifications ─────────────────────────────────────────

spec_base <- list(
  mu_fn = base_mu,
  theta_fn = base_theta,
  sigma_fn = base_sigma,
  coupling_fn = NULL,
  label = "Base"
)

spec_combined <- list(
  mu_fn = function(q_idx, t, r_prev) {
    base_mu(q_idx, t, r_prev) + 0.03 * sin(2 * pi * t / (18 * 12)) / 12
  },
  theta_fn = function(q_idx, t, r_prev) {
    ifelse(r_prev < base_mu(q_idx, t, r_prev), 0.10, 0.03)
  },
  sigma_fn = function(q_idx, t, r_prev) {
    base_sigma(q_idx, t, r_prev) * (1 + 2 * pmax(r_prev * 12, 0))
  },
  coupling_fn = NULL,
  label = "Combined"
)

spec_diffusion <- list(
  mu_fn = base_mu,
  theta_fn = base_theta,
  sigma_fn = base_sigma,
  coupling_fn = function(r_prev) 0.03 * discrete_laplacian(r_prev),
  label = "Diffusion"
)

spec_spatial_ar <- list(
  mu_fn = base_mu,
  theta_fn = base_theta,
  sigma_fn = base_sigma,
  coupling_fn = function(r_prev) {
    n <- length(r_prev)
    pull <- numeric(n)
    pull[1:(n - 1)] <- 0.05 * (r_prev[2:n] - r_prev[1:(n - 1)])
    pull
  },
  label = "Spatial AR"
)

spec_credit <- list(
  mu_fn = function(q_idx, t, r_prev) {
    sensitivity <- 0.5 + 2.0 * (q_idx / max(q_idx))^2
    base_mu(q_idx, t, r_prev) + sensitivity * credit_series[t] / 12
  },
  theta_fn = base_theta,
  sigma_fn = base_sigma,
  coupling_fn = NULL,
  label = "Credit-leverage"
)

specifications <- list(
  spec_base,
  spec_combined,
  spec_diffusion,
  spec_spatial_ar,
  spec_credit
)

all_labels <- c(
  "Base",
  "Combined",
  "Diffusion",
  "Spatial AR",
  "Credit-leverage"
)
strong_labels <- c("Diffusion", "Spatial AR", "Credit-leverage")

correlation_lengths <- c(5, 15, 30)

## ── Run simulations ──────────────────────────────────────────────

cat("Running simulations...\n")

all_sims <- expand_grid(
  spec_idx = seq_along(specifications),
  cor_length = correlation_lengths
) |>
  pmap(\(spec_idx, cor_length) {
    spec <- specifications[[spec_idx]]
    cat(sprintf("  %s (cor = %d)\n", spec$label, cor_length))
    simulate_null(
      n_quantiles,
      n_months,
      cor_length,
      initial_prices,
      spec$mu_fn,
      spec$theta_fn,
      spec$sigma_fn,
      spec$coupling_fn,
      spec$label
    ) |>
      mutate(cor_length = cor_length)
  }) |>
  bind_rows()

## ── Compute growth ranks ─────────────────────────────────────────

cat("Computing growth ranks...\n")

all_sims_ranked <-
  all_sims |>
  group_by(label, cor_length, quantile) |>
  arrange(month) |>
  mutate(
    log_return = log_price - lag(log_price, 12),
    ma12 = slide_dbl(
      log_return,
      mean,
      .before = 5,
      .after = 6,
      .complete = FALSE
    ),
    ma2x12 = slide_dbl(ma12, mean, .before = 1, .after = 0, .complete = FALSE)
  ) |>
  ungroup() |>
  drop_na() |>
  group_by(label, cor_length, month) |>
  mutate(growth_rank = row_number(desc(ma2x12))) |>
  ungroup() |>
  mutate(year = 1995 + month / 12)

## ── Diagnostics: wave peak trajectory ────────────────────────────
## §4.5 predicts q*(t) follows a logistic trajectory through
## quantile space. In the nulls, q*(t) should be noisy.

cat("Computing diagnostics...\n")

wave_peaks <-
  all_sims_ranked |>
  filter(cor_length == 15) |>
  group_by(label, month) |>
  slice_max(ma2x12, n = 1, with_ties = FALSE) |>
  ungroup() |>
  select(label, month, year, peak_quantile = quantile)

## ── Diagnostics: directional asymmetry ───────────────────────────
## §4.4 predicts v < 0: propagation from expensive → cheap.

directional_asymmetry <-
  all_sims_ranked |>
  filter(cor_length == 15) |>
  group_by(label, quantile) |>
  arrange(month) |>
  mutate(rank_change = growth_rank - lag(growth_rank)) |>
  ungroup() |>
  filter(!is.na(rank_change), quantile < n_quantiles) |>
  inner_join(
    all_sims_ranked |>
      filter(cor_length == 15) |>
      group_by(label, quantile) |>
      arrange(month) |>
      mutate(rank_change_above = growth_rank - lag(growth_rank)) |>
      ungroup() |>
      filter(!is.na(rank_change_above)) |>
      mutate(quantile = quantile - 1) |>
      select(label, month, quantile, rank_change_above),
    by = c("label", "month", "quantile")
  ) |>
  summarise(
    downward = mean(rank_change < 0 & rank_change_above > 0, na.rm = TRUE),
    upward = mean(rank_change < 0 & rank_change_above < 0, na.rm = TRUE),
    .by = label
  ) |>
  mutate(asymmetry = downward / (downward + upward))

cat(
  "\nDirectional asymmetry (0.5 = symmetric; > 0.5 = expensive \u2192 cheap):\n\n"
)
print(directional_asymmetry, n = Inf)
cat("\n")

## ── Plots ─────────────────────────────────────────────────────────

cat("Creating plots...\n")

plot_heatmap <- function(data, spec_label, cor_len) {
  data |>
    filter(label == spec_label, cor_length == cor_len) |>
    plot_ly(
      x = ~year,
      y = ~quantile,
      z = ~ -growth_rank,
      type = "heatmap",
      colorscale = "RdBu",
      showscale = FALSE
    ) |>
    layout(
      xaxis = list(title = ""),
      yaxis = list(title = "", ticks = "", showticklabels = FALSE)
    )
}

# 1. Main comparison: all 5 models at cor = 15

p_main <- subplot(
  map(all_labels, \(lab) plot_heatmap(all_sims_ranked, lab, 15)),
  nrows = 5,
  shareX = TRUE
)
p_main

# 2. Wave peak trajectory q*(t)

p_peaks <- subplot(
  map(all_labels, function(lab) {
    d <- wave_peaks |> filter(label == lab)
    lo <- loess(peak_quantile ~ year, data = d, span = 0.3)
    d$smooth <- predict(lo)

    plot_ly(
      d,
      x = ~year,
      y = ~peak_quantile,
      type = "scatter",
      mode = "markers",
      marker = list(size = 3, opacity = 0.3, color = "steelblue"),
      showlegend = FALSE
    ) |>
      add_trace(
        x = ~year,
        y = ~smooth,
        mode = "lines",
        line = list(color = "firebrick", width = 2),
        showlegend = FALSE
      ) |>
      layout(
        yaxis = list(title = ""),
        xaxis = list(title = "")
      )
  }),
  nrows = 5,
  shareX = TRUE
)
p_peaks

# 3. Sensitivity: strong nulls x 3 correlation lengths

p_sens <- subplot(
  expand_grid(lab = strong_labels, cl = correlation_lengths) |>
    pmap(\(lab, cl) plot_heatmap(all_sims_ranked, lab, cl)),
  nrows = 3
)
p_sens

# 4. Spatial AR parameter sweep

cat("Running Spatial AR parameter sweep...\n")

ar_betas <- c(0.02, 0.05, 0.10, 0.20, 0.35, 0.50)

ar_sweep <- map(ar_betas, \(beta) {
  cat(sprintf("  beta = %.2f\n", beta))
  simulate_null(
    n_quantiles,
    n_months,
    15,
    initial_prices,
    base_mu,
    base_theta,
    base_sigma,
    coupling_fn = function(r_prev) {
      n <- length(r_prev)
      pull <- numeric(n)
      pull[1:(n - 1)] <- beta * (r_prev[2:n] - r_prev[1:(n - 1)])
      pull
    },
    label = sprintf("\u03B2 = %.2f", beta)
  ) |>
    mutate(cor_length = 15)
}) |>
  bind_rows()

ar_sweep_ranked <-
  ar_sweep |>
  group_by(label, cor_length, quantile) |>
  arrange(month) |>
  mutate(
    log_return = log_price - lag(log_price, 12),
    ma12 = slide_dbl(
      log_return,
      mean,
      .before = 5,
      .after = 6,
      .complete = FALSE
    ),
    ma2x12 = slide_dbl(ma12, mean, .before = 1, .after = 0, .complete = FALSE)
  ) |>
  ungroup() |>
  drop_na() |>
  group_by(label, cor_length, month) |>
  mutate(growth_rank = row_number(desc(ma2x12))) |>
  ungroup() |>
  mutate(year = 1995 + month / 12)

p_ar_sweep <- subplot(
  map(sprintf("\u03B2 = %.2f", ar_betas), \(lab) {
    ar_sweep_ranked |>
      filter(label == lab) |>
      plot_ly(
        x = ~year,
        y = ~quantile,
        z = ~ -growth_rank,
        type = "heatmap",
        colorscale = "RdBu",
        showscale = FALSE
      ) |>
      layout(
        xaxis = list(title = ""),
        yaxis = list(title = "", ticks = "", showticklabels = FALSE)
      )
  }),
  nrows = 2
)
p_ar_sweep

cat("Done.\n")
